### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by fighterii** [hpssjellis/tensorflow-udacity-deep-learning#3]
Installation on c9 fails. 

(actually there are a couple of red lines before, but this is the error where the installation routine aborts)

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/jupyter-1.0.0.dist-info'

Storing debug log for failure in /home/ubuntu/.pip/pip.log
setup.sh: line 135: jupyter: command not found
```

**Comment by hpssjellis** [comment]
Can you try the super long installation at 

https://github.com/hpssjellis/forth-tensorflow

It is my forth attempt. It is better but takes ages to install.

**Comment by fighterii** [comment]
Yes, this installation worked for me.

And it even didn`t take that long. Thank you.

**Comment by hpssjellis** [comment]
That is great. I was wondering if all three repos would not work becuas3e tensorflow has moved to version 0.9

I wonder what is wrong with the other repo?

**Comment by gregorydillon** [comment]
This worked for me when I used the setup-old.sh but not when I used the current setup.sh..

**Comment by hpssjellis** [comment]
Glad that it worked, but that probably is an old version of Tensorflow. I think yensorflow is at version .10 now.

I will try to have a look at it.
